services:
  - type: web
    name: video-wall-real-player
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
